[package]
name = "ttpkit-io"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1"
futures = "0.3"
pin-project-lite = "0.2"

[dependencies.tokio]
version = "1"
features = ["io-util", "time"]
